In [0]:
!pip install transformers

     |████████████████████████████████| 552kB 3.5MB/s 
     |████████████████████████████████| 1.0MB 19.4MB/s 
     |████████████████████████████████| 3.7MB 21.6MB/s 
     |████████████████████████████████| 870kB 40.4MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.38-cp36-none-any.whl size=884628 sha256=3f30e9ca8ad96ebc5cff422bab3768414ad83a306879ff4881b072e3708fef1a
  Stored in directory: /root/.cache/pip/wheels/6d/ec/1a/21b8912e35e02741306f35f66c785f3afe94de754a0eaf1422
Successfully built sacremoses


In [0]:
import torch
from transformers import BertModel,BertTokenizer

In [0]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')


'''

#encoded = tokenizer.encode('who was jim henson',add_special_tokens=True)


indexed_tokens = torch.tensor([tokenizer.convert_tokens_to_ids(tokenized_text)])
indexed_tokens

indexed_tokens.shape


model = BertModel.from_pretrained('bert-base-uncased')
model.eval()

outputs = None
with torch.no_grad():
  outputs = model(indexed_tokens)



outputs[0].shape
#outputs[1].shape



In [0]:

question = ["How much is jacob paid",
            "What is the total salary of jacob",
          ]

cols = [  [ 'id','name','total salary' ], [ 'id','name','total salary'], ]





In [0]:
import numpy as np


batch_question_word_id = []
batch_size = len(question)

for cur in question:
  batch_question_word_id.append(tokenizer.encode(cur,add_special_tokens=True))

print(batch_question_word_id)


q_len = np.zeros((batch_size),dtype=np.int_)
for i in range(len(batch_question_word_id)):
  q_len[i] = len(batch_question_word_id[i])

maximum_length = max( len(x) for x in batch_question_word_id )
print(maximum_length)


print(q_len)


[[101, 2129, 2172, 2003, 6213, 3825, 102], [101, 2054, 2003, 1996, 2561, 10300, 1997, 6213, 102]]
9
[7 9]


In [0]:
import numpy as np

batch_embedding = np.zeros((batch_size,maximum_length),dtype=np.int_)
for i in range(batch_size):

  batch_embedding[i,:len(batch_question_word_id[i])] = batch_question_word_id[i]

print(batch_embedding)

[[  101  2129  2172  2003  6213  3825   102     0     0]
 [  101  2054  2003  1996  2561 10300  1997  6213   102]]


In [0]:
question_embedding = torch.tensor(batch_embedding)
print(question_embedding.shape)

torch.Size([2, 9])


In [0]:
model = BertModel.from_pretrained('bert-base-uncased')
model.eval()

outputs = None
with torch.no_grad():
  outputs = model(question_embedding)
  

In [0]:
outputs[0].shape


torch.Size([2, 9, 768])

In [0]:
col_len = np.zeros((batch_size),dtype=np.int_)
for i in range(batch_size):

  col_len[i] = len(cols[i])

print(col_len)

[3 3]


In [0]:
column_embeddings = [] 

with torch.no_grad():
  

  for b in range(batch_size):
    current_ques = []
    for c in cols[b]:
      encoded_name = torch.tensor([tokenizer.encode(c,add_special_tokens=True)])
      encoded = model(encoded_name)
      current_ques.append(encoded[1][0])

    column_embeddings.append(current_ques)


print(column_embeddings[0])






[tensor([-9.1390e-01, -2.6067e-01, -1.6177e-01,  8.6036e-01, -2.3931e-01,
        -9.2996e-02,  9.3982e-01,  1.4347e-01, -1.5215e-01, -9.9997e-01,
        -2.3034e-01,  7.5573e-01,  9.8750e-01,  1.5271e-01,  9.4250e-01,
        -6.4603e-01, -5.0243e-01, -4.9210e-01,  4.6132e-01, -8.5394e-01,
         6.6645e-01,  9.9549e-01,  5.4160e-01,  2.4272e-01,  4.8839e-01,
         9.0172e-01, -6.9724e-01,  9.5383e-01,  9.6663e-01,  7.4506e-01,
        -8.0295e-01,  1.2239e-01, -9.9282e-01, -2.8215e-01, -3.9581e-01,
        -9.9138e-01,  2.8494e-01, -8.3428e-01, -2.4879e-03,  8.8365e-02,
        -9.2930e-01,  2.3227e-01,  9.9976e-01,  3.2397e-01,  1.9170e-01,
        -3.5573e-01, -1.0000e+00,  2.1411e-01, -9.1079e-01,  4.2392e-01,
         2.2255e-01, -1.2050e-01,  1.2537e-01,  4.1669e-01,  5.1614e-01,
         3.8794e-01, -1.3235e-01,  1.2139e-01, -1.9305e-01, -6.1237e-01,
        -6.4926e-01,  5.1568e-01, -4.3699e-01, -8.9856e-01,  2.2986e-01,
         5.7683e-02, -1.2858e-01, -2.1665e-01, -3.

In [0]:
len(column_embeddings)

2

In [0]:
len(column_embeddings[0]
    )

3

In [0]:
column_embeddings[0][0].shape

torch.Size([768])

In [0]:
print(column_embeddings[0][1].shape)

torch.Size([768])


In [0]:
max_col_length  = max(col_len)
type(int(max_col_length))

int

In [0]:
max_col_length  = int(max(col_len))

column = torch.zeros((batch_size,max_col_length,768))

for b in range(batch_size):
  for l in range(int(col_len[b])):
    column[b,l,:] = column_embeddings[b][l]



In [0]:
column[0][0]

tensor([-9.1390e-01, -2.6067e-01, -1.6177e-01,  8.6036e-01, -2.3931e-01,
        -9.2996e-02,  9.3982e-01,  1.4347e-01, -1.5215e-01, -9.9997e-01,
        -2.3034e-01,  7.5573e-01,  9.8750e-01,  1.5271e-01,  9.4250e-01,
        -6.4603e-01, -5.0243e-01, -4.9210e-01,  4.6132e-01, -8.5394e-01,
         6.6645e-01,  9.9549e-01,  5.4160e-01,  2.4272e-01,  4.8839e-01,
         9.0172e-01, -6.9724e-01,  9.5383e-01,  9.6663e-01,  7.4506e-01,
        -8.0295e-01,  1.2239e-01, -9.9282e-01, -2.8215e-01, -3.9581e-01,
        -9.9138e-01,  2.8494e-01, -8.3428e-01, -2.4879e-03,  8.8365e-02,
        -9.2930e-01,  2.3227e-01,  9.9976e-01,  3.2397e-01,  1.9170e-01,
        -3.5573e-01, -1.0000e+00,  2.1411e-01, -9.1079e-01,  4.2392e-01,
         2.2255e-01, -1.2050e-01,  1.2537e-01,  4.1669e-01,  5.1614e-01,
         3.8794e-01, -1.3235e-01,  1.2139e-01, -1.9305e-01, -6.1237e-01,
        -6.4926e-01,  5.1568e-01, -4.3699e-01, -8.9856e-01,  2.2986e-01,
         5.7683e-02, -1.2858e-01, -2.1665e-01, -3.0

In [0]:
# outputs , column

# WHERE no of conditions maximum_length  max_col_length

import torch
import torch.nn as nn 
import torch.nn.functional as F

one_output_fc = nn.Linear(768,1)
less_dimension_1 = nn.Linear(768,100)
less_dimension_2 = nn.Linear(768,100)

col_att_val = one_output_fc(column).squeeze()

for b in range(batch_size):
  if col_len[b] < max_col_length:
    col_att_val[b,col_len[b]:] =  -10000



col_att = F.softmax(col_att_val,dim=1)



context = (column * col_att.unsqueeze(2).expand_as(column)).sum(1)

h = less_dimension_1(context).unsqueeze(0)
h = h.contiguous()  # Need to detach and reshape
c = less_dimension_2(context).unsqueeze(0).contiguous()  # Need to detach and reshape  continguous

lstm = nn.LSTM(768,100,batch_first=True)

out, hidden = lstm(outputs[0],(h,c))

one_output_fc_q = nn.Linear(100,1)


q_att_val = one_output_fc_q(out).squeeze()

for b in range(batch_size):
  if q_len[b] < maximum_length:
    q_att_val[b,q_len[b]:] = -10000

q_att = F.softmax(q_att_val,dim=1)

q_context = (outputs[0] * q_att.unsqueeze(2).expand_as(outputs[0])).sum(1)

less_dimension_q_context = nn.Linear(768,100)
no_condition_layer = nn.Linear(100,5)

final_no_out = no_condition_layer(torch.tanh(less_dimension_q_context(q_context)))
final_no_out  = F.softmax(final_no_out,dim=1)
final_no_out




tensor([[0.2036, 0.2043, 0.1866, 0.1933, 0.2122],
        [0.2022, 0.1866, 0.1891, 0.2100, 0.2121]], grad_fn=<SoftmaxBackward>)

In [0]:
q_context.shape

torch.Size([2, 768])

In [0]:
column.shape

torch.Size([2, 3, 768])

In [0]:
outputs[0].shape

torch.Size([2, 9, 768])

In [0]:
s_n_c = torch.matmul(column, outputs[0].transpose(2,1))

for b in range(batch_size):
  if q_len[b]< maximum_length:
    s_n_c[b,:,q_len[b]:] = -10000

p_n_c = F.softmax(s_n_c,dim=2)

print(p_n_c.shape)
print(outputs[0].shape)

torch.Size([2, 3, 9])
torch.Size([2, 9, 768])


In [0]:
p_n_c = p_n_c.unsqueeze(3)
wenc_n = outputs[0].unsqueeze(1)
c_n = torch.mul(wenc_n,p_n_c)
c_n = c_n.sum(2)
c_n.shape

torch.Size([2, 3, 768])

In [0]:
column.shape

torch.Size([2, 3, 768])

In [0]:
y = torch.cat([column,c_n] ,dim=2)   # must do another linear transform on each
y = torch.tanh(y)

# 2*768 = 1536

In [0]:
y = nn.Linear(1536,1)(y).squeeze(2)
y.shape

torch.Size([2, 3])

In [0]:


## WHERE OPerator

